### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by yserictsai** [yserictsai/DEEPE#1]
DEEPE 手動交易策略

Signal Detection Function
- [x] Hammer and Star
- [x] Double Engulfing
- [x] Single Engulfing
- [x] Huge Solid

Filter Function
- [x] Resonance Filter for Hammer and Star
- [x] Size Filter by ATR
- [x] size Filter by Percentage
- [x] Trend Filter
- [x] swing trend high low filter
- [x] High-Timeframe Filter
- [x] swing highest lowest filter
- [x] Volume Filter
- [x]  RSI filter

Stop Loss Function
- [x] 停損設置 - 固定點數法
- [x] 停損設置 - 漲跌幅%法
- [x] 停損設置 - 波動ATR法
- [x] 停損設置 - 前高前低法
- [x] TP/SL Draw

Trailing Stop Function
- [ ] 移動停利 - 固定RR法
- [ ] 移動停利 - 漲跌幅%法
- [ ] 移動停利 - 波動ATR法
- [ ] 移動停利 - Drawdown %
- [ ] 反向K線型態

Strategy Evaluation Table
- [ ] Table display
        * Win rate
        * Profit factor
        * Max. drawdown
        * Day Evalutaion
        * Session Evaluation
        * Max. RR
        * time session filter
        * day filter

進階
- [ ] 判斷N字上漲
- [ ] 判斷空間 過漲 過跌
- [ ] 多空漲跌混亂
- [ ] 大週期的支撐壓力
- [ ] Position size
- [ ] 加密貨幣的倉位計算
- [ ] FOREX 的倉位計算
- [ ] Low-Timeframe Filter
  - [ ] 1. Trend 同向
  - [ ] 2. 小週期壓縮
